# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.remote.webelement import WebElement



class TestRobot():
  def setup_method(self, method):
    self.driver = webdriver.Chrome('/home/pedro/Downloads/chromedriver')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_robot(self):
    self.driver.get("https://www.cifraclub.com.br/musico/42155909/repertorio/4900357/")
    self.driver.set_window_size(1873, 1053)
    #self.driver.find_element(By.LINK_TEXT, "").click()
    #self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) > .small > label").click()
    #self.vars["window_handles"] = self.driver.window_handles
    #self.driver.find_element(By.ID, "js-print").click()
    #self.vars["win4999"] = self.wait_for_window(2000)
    #self.driver.switch_to.window(self.vars["win4999"])
    #self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) label").click()
    #self.driver.find_element(By.ID, "t_imprimir").click()

def wait_for_window(driver, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = driver.window_handles
    wh_then = vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()

def main():

    chrome_options = webdriver.ChromeOptions()
    settings = {
           "recentDestinations": [{
                "id": "Save as PDF",
                "origin": "local",
                "account": "",
            }],
            "selectedDestinationId": "Save as PDF",
            "version": 2
        }
    prefs = {'printing.print_preview_sticky_settings.appState': json.dumps(settings)}
    chrome_options.add_experimental_option('prefs', prefs)
    chrome_options.add_argument('--kiosk-printing')
    driver = webdriver.Chrome('/home/pedro/Downloads/chromedriver', chrome_options=chrome_options)
    driver.get("https://www.cifraclub.com.br/musico/42155909/repertorio/4900357/")
    window_before = driver.window_handles[0]
    #driver.set_window_size(1873, 1053)
    PlajePariuri = driver.find_elements_by_xpath("//ol[@class='list-links list-musics']/li/a")
    links = []
    for i in range(len(PlajePariuri)):
      links.append(PlajePariuri[i].get_attribute("href"))
    print(links[82])

    for i in range(89, len(PlajePariuri)):
    #for items in PlajePariuri:
        #print (items.get_attribute("href"))
        #driver.get(items.get_attribute("href"))
        driver.get(links[i])
        window_before1 = driver.window_handles[0]
        time.sleep(3)
        #driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) > .small > label").click()
        driver.find_element_by_xpath('//button[text()="Exibir"]').click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) > .small > label").click()
        time.sleep(1)
        driver.find_element(By.ID, "js-print").click()
        window_after = driver.window_handles[1]
        time.sleep(3)
        driver.switch_to.window(window_after)
        time.sleep(1)
        driver.find_element(By.ID, "side-exibir").click()
        time.sleep(1)
        driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) label").click()
        time.sleep(1)
        driver.execute_script('window.print();')
        time.sleep(3)
        driver.close()
        driver.switch_to.window(window_before1)

if __name__ == "__main__":
    main()  
